title: "Obed Mokua Nyandiri
theme: jekyll-theme-minimal
description: >
  Machine Learning Engineer | Data Scientist | AI Solutions Developer
  Specializing in predictive analytics and intelligent system design
url: "https://ObedMokuaNyandiri.github.io"

